aione/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from ytDownloader import views as yt_v
from aione import views as aione_v
from converter import views as co_v
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('YT-Video', yt_v.ytd, name="ytd"),
    # path('index', dom_v.homep),
    path('', aione_v.homep),
    path('aione-services', aione_v.aiservice, name="aione-services"),
    path('aione-contact-us', aione_v.aicontact, name="aione-contact-us"),
    path('aione-about-us', aione_v.aiabout, name="aione-about-us"),
    path('Aione-Home', aione_v.aione, name="Aione-Home"),
    path('Video-Details', co_v.videodetails, name="Video-Details"),
    path('video-to-audio', co_v.downloadmp3, name="video-to-audio"),
    path('video2audio', co_v.video2audio, name="video2audio"),
    path('downloadmp3', co_v.downloadmp3, name="downloadmp3"),
    # domain checker
    # path('domain-informations', do_v.domain, name="domain-informations"),

	path('download/', yt_v.download_page, name="download"),
	path('download/<res>/', yt_v.success, name="success"),
    path('', include('ytDownloader.urls')),
    path('', include('converter.urls')),
    # path('', include('doinf.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]

ytDownloader/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'YT-downloader'

urlpatterns = [
	path('', views.ytd, name="ytd"),
	path('ytd', views.ytd, name="ytd"),
	path('download/', views.download_page, name="download"),
	path('download/<res>/', views.success, name="success"),
	path('about/', views.about, name="about"),
	path('music/', views.music, name="music"),
	path('download-music/', views.download_music, name="download-music"),
	path('download-playlist/', views.playlist, name="download-playlist"),
	path('contact/', views.contact, name='contact'),
]

ytDownloader/models.py
from django.db import models

# Create your models here.

ytDownloader/views.py
from django.shortcuts import render
from django.http import HttpResponse
from pytube import YouTube, Playlist
import os
from wsgiref.util import FileWrapper
import shutil
from django.contrib import messages
from requests import request

from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
import re


# Create your views here.

def ytd(request):
    return render(request, 'ytd.html')


def download_page(request):
    global url
    url = request.GET.get('url')
    regex = r'(https?\:\/\/)?(www\.)?(youtube\.com|youtu\.?be)\/.+'
    if not re.match(regex, url):
        return render(request, 'ytd.html' ,{'error':True})
    yt = YouTube(url)
    global streams
    streams = yt.streams

    res = []
    ores = []
    for i in streams:
        onlyres = i.resolution

        string = str(i.resolution) + ' ' + \
            str(i.filesize_approx // 1048576) + 'mb'

        res.append(string)
        ores.append(onlyres)

    ores = list(dict.fromkeys(ores))

    try:
        for j in range(len(ores)):
            if ores[j] == None:
                ores.pop(j)

    except:
        pass

    for k in range(len(ores)):
        ores[k] = ores[k] + ' ' + \
            str(streams.filter(res=ores[k]).first().filesize // 1048576) + 'mb'

    title = yt.title
    author = yt.author
    length = str(yt.length//60) + ' minutes'
    if length == 0:
        length = str(yt.length) + ' seconds'

    thumbnail = yt.thumbnail_url
    print(thumbnail)

    res = list(dict.fromkeys(res))

    return render(request, 'download.html', {
        'onlyres': ores,
        'res': res,
        'title': title,
        'author': author,
        'length': length,
        'thumbnail': thumbnail,
    })


def success(request, res):
    global url

    homedir = os.path.expanduser("~")

    dirs = homedir + '/Downloads/'

    yt = YouTube(url)
    title = yt.title
    print(title)
    res, b = res.split()
    size = streams.filter(res=res).first().filesize // 1048576
    print(size)
    if request.method == 'POST' and size < 900:

        streams.filter(res=res).first().download(
            output_path=dirs, filename="video.mp4")
        file = FileWrapper(open(f'{dirs}/video.mp4', 'rb'))
        # path =  '/home/runner/youtube-video-downloader/downloads/video' + '.mp4'
        # o = dirs + title + '.mp4'
        response = HttpResponse(file, content_type='application/vnd.mp4')
        response['Content-Disposition'] = 'attachment; filename = "video.mp4"'
        os.remove(f'{dirs}/video.mp4')
        return response
        # return render(request, 'success.html')

    else:
        return render(request, 'error.html')


def about(request):
    return render(request, 'about.html')


def music(request):
    return render(request, 'music.html')


def download_music(request):
    url = request.GET.get('url')
    yt = YouTube(url)
    title = yt.title

    stream = yt.streams.filter(only_audio=True).first()
    # size = stream.filesize

    homedir = os.path.expanduser("~")

    dirs = homedir + '/Downloads/'
    size = stream.filesize // 1048576

    # messages.success(request, 'The download has been started, do not close this page')
    if request.method == 'POST' and size < 900:
        stream.download(output_path=dirs, filename=f"{title}.mp3")
        file = FileWrapper(open(f'{dirs}/{title}.mp3', 'rb'))
        # path =  '/home/runner/youtube-video-downloader/downloads/video' + '.mp4'
        # o = dirs + title + '.mp4'
        response = HttpResponse(file, content_type='audio.mp3')
        response['Content-Disposition'] = f'attachment; filename = "{title}.mp3"'
        os.remove(f'{dirs}/{title}.mp3')
        return response
    # return render(request, 'success.html')
    else:
        return render(request, 'error.html')


def playlist(request):

    url = request.GET.get('url')

    playlist = Playlist(url)
    title = playlist.title
    videos = playlist.videos

    homedir = os.path.expanduser("~")

    dirs = homedir + f'/Downloads'

    size = 0

    for i in videos:
        stream = i.streams.filter(only_audio=True).first()
        size += stream.filesize // 1048576

    # messages.success(request, 'The download has been started, do not close this page')
    if size < 900:
        for i in videos:
            name = i.title
            stream = i.streams.filter(only_audio=True).first()
            stream.download(
                output_path=f'{dirs}/{title}', filename=f"{name}.mp3")

        path = shutil.make_archive(title, 'zip', f'{dirs}/{title}')

        file = FileWrapper(open(path, 'rb'))

        response = HttpResponse(
            file, content_type='application/force-download')
        response['Content-Disposition'] = f'attachment; filename = "{title}.zip"'
        os.remove(path)
        os.remove(f'{dirs}/{title}')
        return response

    else:
        return render(request, 'error.html')


def contact(request):
    return render(request, 'contact.html')

ytDownloader/templates/about.html
{% extends 'layout.html' %}

{% block content %}
<div class="heading">
	About this site	
</div>

<div class="ct">
	This site downloads yt videos
</div>
{% endblock %}

ytDownloader/templates/contact.html
{% extends 'layout.html' %}

{% block content %}
<h2 style="padding-top: 50px;" class="ct">
	Contact Me
</h2>
<div class="contact">
<form class="forms" action="https://formsubmit.co/dev.marvel.avengers@gmail.com" method="post" autocomplete="off">
		
	<label for="name" >Your Name</label>
	<input type="text" name="name" class="input" placeholder="Your Name" required>

	<label for="email">Email</label>
	<input type="email" class="input" name="email" placeholder="Email" required>

	<label for="message">Message</label>
	<textarea name="message" placeholder="Message"></textarea required>

	<input class="input" type="submit" value="Submit">

</form>
</div>
{% endblock %}

ytDownloader/templates/download.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
	<section class="about">
		<div class="container" data-aos="fade-up">
	
		  <div class="section-title">
			<h2>Your YouTube Video</h2>
		</div>

		<div class="container text-center">
			<div class="row">
			  <div class="col-12 col-lg-6 col-sm-12">
				<div class="thumbnail">
					<img class="thumbnail-image" src="{{thumbnail}}" alt="Error loading thumnnail" style="border-radius: 11px;">
				</div>
			  </div>
	<div class="col-12 col-lg-6 col-sm-12">
				
		<div class="row ct">
			<div class="col-12">
				<span class="span1">Title:</span> <br> {{title}}
			</div>
			<br>
			<br>
			<div class="col-12">
				<span class="span1">Posted By:</span> <br> {{author}}
			</div>
			<br>
			<br>
			<div class="col-12">
				<span class="span1">Video Length:</span> <br> {{length}}
			</div>
			<br>
			<br>
		</div>
			  </div>
			</div>
		  </div>
	
		  	
		  <div class="section-title">
			<h2 style="margin-top:50px;">Chose video downloading format</h2>
		</div>
	
				
		<table>
			<thead>
				<tr class="table-heading">
					<th scope="col" style="color: black;">Format</th>
					<th scope="col" style="color: black;">Download</th>
				</tr>
			</thead>

			{% for i in onlyres %}

			<tbody>
				<tr>
					<td data-label="Attributes">{{i}}</td>
					<td data-label="Download">
						<form action="{% url 'YT-downloader:success' i %}" method="post">
							{% csrf_token %}
							<button type="submit" value="Download" class="download-btn">Download</button>
						</form>
					</td>
				</tr>

				{% endfor %}

			</tbody>
		</table>

		</div>
	</section>
</div>
		

{% endblock %}

ytDownloader/templates/error.html
404 not found

ytDownloader/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>YT Video Download</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'styles.css' %}?{% now "U" %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
		  <!-- Favicons -->
		  <link href="static/book.png" rel="icon">
		  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
		  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	</head>
	<body class="home-page">
	  <!-- ======= Header ======= -->
	  <header id="header" class="fixed-top ">
		<div class="container d-flex align-items-center">
	
		  <h1 class="logo me-auto"><a href="i">AI-ONE</a></h1>
		  <nav class="navbar">
			<ul>
			  <li><a class="nav-link scrollto" href="/">Home</a></li>
			  <li><a class="nav-link scrollto" href="#">Services</a></li>
			  <li><a class="nav-link scrollto" href="#contact">Contact Us</a></li>
			  <li><a class="nav-link scrollto" href="#about">About Us</a></li>
			</ul>
			<a class="nav-link scrollto" href="#">Services</a>
		  </nav><!-- .navbar -->
	
		</div>
	  </header><!-- End Header -->
	

		{% block content %}
		{% endblock %}

		  <!-- ======= Footer ======= -->
		  <footer id="footer">

		
			<div class="footer-top">
			  <div class="container">
				<div class="row">
		
		
				  <div class="col-lg-4 col-md-6 footer-links">
					<h4>AIONE</h4>
					<p style="font-family:sans-serif;font-size:15px;">AIONE is a Open-Ai website.We provide different tools which you need.Our mission is to assist you with answering your questions, providing information, and engaging in conversation.</p>
				  </div>
		
		
				  <div class="col-lg-4 col-md-6 footer-links">
					<h4>Quick Links</h4>
					<ul>
					  <li> <a href="/Aione-Home" style="font-family:sans-serif;">Home</a></li>
					  <li> <a href="/aione-about-us"  style="font-family:sans-serif"> About us</a></li>
					  <li> <a href="/aione-services" style="font-family:sans-serif;">Services</a></li>
					  <li> <a href="#" style="font-family:sans-serif;">Terms of service</a></li>
					  <li> <a href="#" style="font-family:sans-serif;">Privacy policy</a></li>
					</ul>
				  </div>
		
				  <div class="col-lg-4 col-md-6 footer-links">
					<h4>Our Services</h4>
					<ul>
					  <li> <a href="/YT-Video" style="font-family:sans-serif;">YouTube Video Downloader</a></li>
					  <li> <a href="/video2audio" style="font-family:sans-serif;">Video 2 Audio Online</a></li>
					  <li> <a href="/Video-Details" style="font-family:sans-serif;">Check Video Details</a></li>
					</ul>
				  </div>
		
				</div>
			  </div>
			</div>
		
			<div class="container footer-bottom clearfix">
			  <div class="copyright" style="font-family:sans-serif;">
				Copyright &copy; 2022 <strong><span>AIONE</span></strong>. All Rights Reserved
			  </div>
			</div>
		  </footer><!-- End Footer -->
		



		</body>

ytDownloader/templates/music.html
{% extends 'layout.html' %}

{% block content %}
		<div class="heading">
			Single Music
		</div>
		
		<form action="/download-music/" class="search-form" method="get">
			<div class="form">
				<!--<label for="link">Enter Link</label>-->
				<input type="text" id="link" name="url"  placeholder="Enter YouTube Video Link" autocomplete="on" required  style="margin: 0 0 1em;
                border: none;
                outline: none;
                width: 90%;
                /* padding: 17px; */
                height: 50px;
                border-radius: 10px;
                padding: 8px;
                background: #6d35dc;
                color: white;
            }">
			</div>
			<button type="submit"  style="    display: block;
			margin-left: auto;
			margin-right: auto;
			padding: 8px;
			width: 30%;
			border: none;
			border-radius: 6px;
			font-family: sans-serif;
			font-size: 19px;
			margin-top: 20px;
			background: #6d35dc;
			color:white;
			">Enter</button>
		</form>

		

{% endblock %}

ytDownloader/templates/ytd.html
{% extends 'layout.html' %}

{% block content %}




<div class="container">
	<section class="about">
		<div class="container" data-aos="fade-up">
	
		  <div class="section-title">
			<h2>Enter YouTube Video link here</h2>
		</div>

		{% if error %}
		<div class="alert alert-danger" style="
		width: 50%;
		align-items: center;
		margin-left: auto;
		margin-right: auto;
	}">
			Please Check Your Video Url
		</div>
		{% endif %}

		<div>
			<form action="download/" class="search-form" method="get">
				<div class="form" style="text-align: center;">
					<input type="text" id="link" name="url" placeholder="Enter Link" required>
				</div>


				<button type="submit">Confirm</button>
			</form>
		</div>
	
	
		</div>
	</section>
</div>

      <!-- ======= About Us Section ======= -->
	  <section class="about">
		<div class="container" data-aos="fade-up">
  
  
		  <div class="row content container">
			<div class="section-title">
				<h2 style="text-align:left;text-transform: capitalize;margin-bottom:0px;">What is a YouTube Video Downloader</h2>
			  </div>
			<div class="text1"> 
			 <p>
				A YouTube video downloader is a tool that allows users to download YouTube videos for offline viewing. It is a software application or online tool that can be used to save YouTube videos to a computer or mobile device. There are many YouTube video downloaders available online, both free and paid.
			 </p>
			</div>  
			<div class="section-title">
				<h2 style="text-align:left;text-transform: capitalize;margin-bottom:0px;">How to Use a YouTube Video Downloader</h2>
			  </div>
			<div class="text1">
			  <p>
				Step 1: Copy the YouTube video link
				Open the YouTube video you want to download and copy the URL link from the address bar.
			  </p> 
			</div>  
			<div class="text1">                
			  <p>
				Step 2: Paste the link into the downloader
				Open the YouTube video downloader and paste the copied link into the designated field.
			  </p>    
			</div>  
			<div class="text1">
			  <p>
				Step 3: Select the format and quality
				Choose the format and quality in which you want to download the video.
			  </p> 
			</div>  
			<div class="text1">
			  <p>
				Step 4: Start the download
				Click on the download button to start the download process. Once the download is complete, the video will be saved to your computer or mobile device.
			  </p> 
			</div>  
			<div class="section-title">
				<h2 style="text-align:left;text-transform: capitalize;margin-bottom:0px;">Benefits of using a YouTube Video Downloader</h2>
			  </div>
			<div class="text1">                
			  <p>
				Convenient: With a YouTube video downloader, you can save your favorite videos and watch them at any time and from any location.
			  </p>
			</div>  
			<div class="text1">               
			  <p>
				Higher Quality: Some YouTube video downloaders allow you to download videos in higher quality than what is available online.
			  </p>
			</div>  
			<div class="text1">
			  <p>
				Ad-Free: When you download a video using a YouTube video downloader, you can watch it without any ads.
			  </p>
			</div>  
		  </div>
  
		</div>
	  </section><!-- End About Us Section -->

		

{% endblock %}